### ISSUE TITLE
AO  image

### ISSUE THREAD

**Issue by AI-student-wl** [husheng12345/Unofficial-NeRF-Supervised-Deep-Stereo#3]
Thank you for your selfless dedication. I have a question about the data and hope to get your help. In the official open-source data, there is an AO (Ambient Occlusion) image. I'm not sure if you have rendered it using the NeRF model. The AO I rendered is all 1 or 0.99999. If you could give me some guidance, I would be extremely grateful. Once again, thank you for your open-source work and I wish you a pleasant life.

**Comment by husheng12345** [comment]
Could you please provide more detailed information, such as which specific NeRF model you are using?

**Comment by AI-student-wl** [comment]
I am using nerfstudio. Below is my code for generating depths
![image](https://github.com/husheng12345/Unofficial-NeRF-Supervised-Deep-Stereo/assets/72002667/bc7ce639-aebd-4cd1-b82c-fbd998d1dc9e)

**Comment by AI-student-wl** [comment]
Sorry, according to my understanding of the paper, weights_ Sum is AO, but after saving it, it's all 1, which confuses me

**Comment by husheng12345** [comment]
Firstly, I must mention that since I have not used nerfstudio myself, I am unable to fully answer your question. 
However, it is common for NeRF implementations to treat the furthest radiance as an opaque wall to ensure that the AO strictly equals 1. Therefore, you would simply remove that "wall" in your calculations to correctly obtain AO values less than 1.

**Comment by AI-student-wl** [comment]
Thank you for your prompt. I will follow this approach to check the code. Thank you for your help
